[package]
name = "codegen"
version = "0.0.0"
edition="2021"

[dependencies]
arrayvec = "0.7.4"
blake3 = "1.5.0"
pest = "2.7.5"
pest_derive = "2.7.5"
smallvec = "1.11.2"
smallstr = "0.3.0"
thiserror = "1.0.50"