[package]
name = "codebiber"
version = "0.0.0"
edition="2021"
license="Apache-2.0"

[dependencies]
arrayvec = "0.7.4"
blake3 = "1.5.0"
pest = "2.7.5"
pest_derive = "2.7.5"
smallvec = "1.11.2"
thiserror = "1.0.50"

[dev-dependencies]
proptest = "1.4.0"
lazy-regex = "3.1.0"